grafana:
  image: grafana/grafana:4.0.1
  ports:
    - "127.0.0.1:3000:3000"
  env_file:
    - docker-compose.env
  links:
    - influxdb
  volumes:
    - "grafana_data:/opt/grafana/data"
    - "grafana_conf:/opt/grafana/conf"
  log_driver: json-file
  log_opt:
    max-size: "64k"
    max-file: "10"

influxdb:
  image: influxdb:1.1-alpine
  ports:
    - "127.0.0.1:8086:8086"
  volumes:
    - "influxdb_data:/var/lib/influxdb"
  log_driver: json-file
  log_opt:
    max-size: "64k"
    max-file: "10"
